services:
  - type: web
    name: sante-publique-carte
    runtime: node
    plan: free
    buildCommand: npm install && node server/db/seed.js
    startCommand: node server/startup.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
